version: '2.3'

services:
  mindlogic:
    image: mindlogic
    runtime: nvidia
    networks: ['mindlogic']
    restart: always
    ports:
      - "6006:6006"
    volumes:
      - "./:/app/"
      
networks: {mindlogic: {}}
